name: Build wedding backend

on:
  push:
    branches: ["main"]
    paths: ["apps/backend/**", "packages/**"]

env:
  IMAGE_NAME: wedding-backend
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
  IMAGE_URI: ghcr.io/${{ github.repository }}/wedding-backend:latest

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker build -f ./.docker/server/Dockerfile \
              -t ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Sign image with Cosign
        run: cosign sign --yes ${{ env.IMAGE_URI }}
        env:
          COSIGN_EXPERIMENTAL: "true"
