import type { Metadata } from "next";
import { MonteCarlo, RobotoSerif } from "@/lib/fonts";
import "./globals.css";
import Providers from "@/context/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bg">
      <body
        className={`${MonteCarlo.variable} ${RobotoSerif.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
