import type { Metadata } from "next";
import { MonteCarlo, RobotoSerif } from "@/lib/fonts";
import "./globals.css";
import { SocketProvider } from "@/context/SocketContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MonteCarlo.variable} ${RobotoSerif.variable} antialiased`}
      >
        <SocketProvider url="ws://localhost:8080/ws">{children}</SocketProvider>
      </body>
    </html>
  );
}
